name: Sync Developer to Main
on:
  schedule:
    - cron: '*/30 * * * *'  # Se ejecuta cada 30 minutos
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Fetch del repositorio remoto
        run: |
          git remote add upstream https://github.com/ghost1999dev/backend-auction.git
          git fetch upstream
      
      - name: Verificar si hay cambios
        id: check_changes
        run: |
          git checkout -b temp-branch upstream/developer
          DIFF=$(git diff main..temp-branch)
          if [ -n "$DIFF" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Merge de la rama developer remota a main local
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git checkout main
          git merge upstream/developer --no-ff -m "Auto-merge de la rama developer remota a main"
      
      - name: Push de los cambios
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git push origin main