name: Sync Developer to Main
on:
  workflow_dispatch:  # Allows manual triggering
  repository_dispatch:
    types: [developer_updated]  # Custom webhook event

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - name: Fetch remote repository
        run: |
          git remote add upstream https://github.com/ghost1999dev/backend-auction.git
          git fetch upstream
      
      - name: Attempt automatic merge
        id: merge_attempt
        run: |
          git checkout main
          # First try a normal merge
          if git merge upstream/developer --allow-unrelated-histories --no-ff -m "Auto-merge from remote developer branch to main"; then
            echo "merge_status=success" >> $GITHUB_OUTPUT
          else
            echo "merge_status=conflict" >> $GITHUB_OUTPUT
            # Abort the failed merge to clean up the state
            git merge --abort
          fi
      
      - name: Alternative strategy - Copy new files
        if: steps.merge_attempt.outputs.merge_status == 'conflict'
        run: |
          # Checkout a temporary branch based on upstream/developer
          git checkout -b temp_branch upstream/developer
          
          # Create directory to store files
          mkdir -p /tmp/upstream_files
          
          # Copy all files except .git
          rsync -av --exclude='.git' ./ /tmp/upstream_files/
          
          # Return to main branch
          git checkout main
          
          # Copy files from upstream/developer to main
          rsync -av --exclude='.git' /tmp/upstream_files/ ./
          
          # Add all changes
          git add .
          
          # Commit with informative message
          git commit -m "Sync: Manually copying files from upstream/developer to main due to merge conflicts"
          
          echo "Note: Manual file copy was performed due to merge conflicts."
      
      - name: Push changes
        run: |
          # Use PAT explicitly in URL to ensure permissions
          remote_url="https://${{ secrets.PAT }}@github.com/JulioAmayaJr/backend.git"
          git remote set-url origin "$remote_url"
          git push origin main