name: Sync Developer to Main

on:
  push:
    branches:
      - developer

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/ghost1999dev/backend-auction.git
          git fetch upstream
          
      - name: Merge developer from upstream into main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout main
          git merge upstream/developer --no-ff --commit -m "Auto-merge from upstream developer to main"
      
      - name: Push changes to your repository
        run: |
          git push origin main
